/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package planifticateur.gui;
import planifticateur.domain.HoraireController;
import java.util.Vector;
/**
 *
 * @author Proprietaire
 */
public class Statistiques extends javax.swing.JFrame {

    private static HoraireController horaireController ;
    /**
     * Creates new form Statistiques
     */
    public Statistiques() {
        initComponents();
        horaireController = null;
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        jTextFieldNbCours .setText("0");
        jTextFieldNbMaxCours .setText("0");
        jTextFieldNbMoyCours .setText("0");
        jTextFieldIndCov .setText("0");
        jTextFieldIndConges.setText("0"); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        jLabelNbCours = new javax.swing.JLabel();
        jLabelNbMaxCours = new javax.swing.JLabel();
        jLabelNBMoyCours = new javax.swing.JLabel();
        jLabelIndCov = new javax.swing.JLabel();
        jLabelIndConges = new javax.swing.JLabel();
        jTextFieldNbCours = new javax.swing.JTextField();
        jTextFieldNbMaxCours = new javax.swing.JTextField();
        jTextFieldNbMoyCours = new javax.swing.JTextField();
        jTextFieldIndCov = new javax.swing.JTextField();
        jTextFieldIndConges = new javax.swing.JTextField();
        jComboBoxJour = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 480));

        MainPanel.setPreferredSize(new java.awt.Dimension(640, 278));

        jLabelNbCours.setText("NB de cours :");

        jLabelNbMaxCours.setText("NB max de cours :");

        jLabelNBMoyCours.setText("NB moy de cours :");

        jLabelIndCov.setText("Indice covoiturage :");

        jLabelIndConges.setText("Indice congestion :");

        jTextFieldNbCours.setEditable(false);
        jTextFieldNbCours.setText("jTextField1");

        jTextFieldNbMaxCours.setEditable(false);
        jTextFieldNbMaxCours.setText("jTextField2");

        jTextFieldNbMoyCours.setEditable(false);
        jTextFieldNbMoyCours.setText("jTextField3");

        jTextFieldIndCov.setEditable(false);
        jTextFieldIndCov.setText("jTextField4");

        jTextFieldIndConges.setEditable(false);
        jTextFieldIndConges.setText("jTextField5");

        jComboBoxJour.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi" }));
        jComboBoxJour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxJourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNbCours)
                    .addComponent(jLabelNbMaxCours)
                    .addComponent(jLabelNBMoyCours)
                    .addComponent(jLabelIndCov)
                    .addComponent(jLabelIndConges))
                .addGap(34, 34, 34)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldIndCov, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(jTextFieldNbMoyCours, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNbMaxCours, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNbCours, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldIndConges))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jComboBoxJour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNbCours)
                    .addComponent(jTextFieldNbCours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxJour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNbMaxCours)
                    .addComponent(jTextFieldNbMaxCours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNBMoyCours)
                    .addComponent(jTextFieldNbMoyCours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIndCov)
                    .addComponent(jTextFieldIndCov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIndConges)
                    .addComponent(jTextFieldIndConges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxJourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxJourActionPerformed
       
        if(horaireController != null)
        {
            int jour = jComboBoxJour.getSelectedIndex();
            Vector<Float> stats = horaireController.getStats(jour);
            
            jTextFieldNbCours .setText(Float.toString(stats.elementAt(0)));
            jTextFieldNbMaxCours .setText(Float.toString(stats.elementAt(1)));
            jTextFieldNbMoyCours .setText(Float.toString(stats.elementAt(2)));
            jTextFieldIndCov .setText(Float.toString(stats.elementAt(3)));
            jTextFieldIndConges.setText(Float.toString(stats.elementAt(4)));

        }
        

  
    }//GEN-LAST:event_jComboBoxJourActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Statistiques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Statistiques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Statistiques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Statistiques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Statistiques().setVisible(true);
            }
        });
    }


    public void initialize(HoraireController hc)
    {
         horaireController= hc ;
         //on affiche lundi par default
        Vector<Float> stats = horaireController.getStats(0);
        
        jTextFieldNbCours .setText(Float.toString(stats.elementAt(0)));
        jTextFieldNbMaxCours .setText(Float.toString(stats.elementAt(1)));
        jTextFieldNbMoyCours .setText(Float.toString(stats.elementAt(2)));
        jTextFieldIndCov .setText(Float.toString(stats.elementAt(3)));
        jTextFieldIndConges.setText(Float.toString(stats.elementAt(4)));

    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JComboBox jComboBoxJour;
    private javax.swing.JLabel jLabelIndConges;
    private javax.swing.JLabel jLabelIndCov;
    private javax.swing.JLabel jLabelNBMoyCours;
    private javax.swing.JLabel jLabelNbCours;
    private javax.swing.JLabel jLabelNbMaxCours;
    private javax.swing.JTextField jTextFieldIndConges;
    private javax.swing.JTextField jTextFieldIndCov;
    private javax.swing.JTextField jTextFieldNbCours;
    private javax.swing.JTextField jTextFieldNbMaxCours;
    private javax.swing.JTextField jTextFieldNbMoyCours;
    // End of variables declaration//GEN-END:variables
}
